# Generated by Django 4.2.7 on 2025-11-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='What needs to be done?', max_length=200)),
                ('completed', models.BooleanField(default=False, help_text='Is this task completed?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When was this todo created?')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When was this todo last updated?')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
