"""
Todo Serializer
---------------
Serializers convert complex data (like Python objects) into JSON format
that can be sent over the internet, and vice versa.

Think of it as a translator between Django and the frontend.
"""

from rest_framework import serializers
from .models import Todo


class TodoSerializer(serializers.ModelSerializer):
    """
    TodoSerializer - Converts Todo objects to/from JSON

    What it does:
    -------------
    1. Converts Python Todo objects → JSON (for sending to frontend)
    2. Converts JSON → Python Todo objects (from frontend requests)
    3. Validates data (ensures required fields are present, correct types, etc.)

    Example transformation:
    -----------------------
    Python object: Todo(id=1, title="Learn Django", completed=False)

    JSON output:
    {
        "id": 1,
        "title": "Learn Django",
        "completed": false,
        "created_at": "2025-11-23T10:30:00Z",
        "updated_at": "2025-11-23T10:30:00Z"
    }
    """

    class Meta:
        """
        Metadata that configures the serializer

        model: Which Django model to serialize (Todo)
        fields: Which fields to include in the JSON
        '__all__' means include all fields from the model
        """
        model = Todo
        fields = '__all__'  # Include all fields: id, title, completed, created_at, updated_at

        # These fields are read-only (can't be set by the frontend)
        # They're automatically generated by Django
        read_only_fields = ['id', 'created_at', 'updated_at']
